platform :ios, '11.0'

use_frameworks!

target 'batm' do
  
  # UI
  pod 'SnapKit', '5.0.1'
  pod 'MBProgressHUD', '1.1.0'
  pod 'FlagPhoneNumber', '0.7.2'
  pod 'GoogleMaps', '3.4.0'
  pod 'QRCodeReader.swift', '10.1.0'
  pod 'Giphy', '1.1.6'
  pod 'Toast-Swift', '5.0.1'

  # Utilities
  pod 'TrustWalletCore', '0.12.22'
  pod 'PhoneNumberKit', '3.0.0'
  pod 'Swinject', '2.7.1'
  pod 'ObjectMapper', '3.5.1'
  pod 'BigNumber', :git => 'https://github.com/mkrd/Swift-Big-Integer.git'
  
  # Rx
  pod 'Moya/RxSwift', '13.0.1'
  pod 'RxOptional', '3.6.2'
  pod 'RxFlow', '1.6.2'
  pod 'RxSwift', '4.5.0'
  pod 'RxCocoa', '4.5.0'
  pod 'RxReachability', '0.1.8'
  
  target 'batmTests' do
    inherit! :search_paths
  end
end
