CREATE TABLE IF NOT EXISTS w_wallet (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    type INT(2) NOT NULL,
    seed_encrypted VARCHAR(255) NOT NULL,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

INSERT INTO w_wallet(type, seed_encrypted) VALUES (1, 'KTYZb1q/7hhrVX6R04i6TBIpEtG4I4qP4PtuKhTJzWHgkDBfmb8aVGw6s5fdZ7gaNLimqIrbTBIUVz24+aDAHT7QQ/19A8OZDv2RTxCE844=');
ALTER TABLE w_coinpath ADD COLUMN wallet_id BIGINT(20) DEFAULT 1 AFTER id;
ALTER TABLE w_coinpath ADD FOREIGN KEY (wallet_id) REFERENCES w_wallet(id);