CREATE TABLE IF NOT EXISTS w_terminallocation (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  address varchar(255) NOT NULL,
  latitude DECIMAL(20, 10) NOT NULL,
  longitude DECIMAL(20, 10) NOT NULL,
  create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;