CREATE TABLE IF NOT EXISTS w_terminallocationhour (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  terminal_location_id BIGINT(20) NOT NULL,
  days VARCHAR(255) DEFAULT NULL,
  hours VARCHAR(255) DEFAULT NULL,
  create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (terminal_location_id) REFERENCES w_terminallocation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
