CREATE TABLE IF NOT EXISTS w_referral (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    user_id BIGINT(20) NOT NULL,
    code VARCHAR(10) DEFAULT NULL,
    invited INT(2) DEFAULT 0,
    earned DECIMAL(20, 10) DEFAULT 0,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES w_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;