CREATE TABLE IF NOT EXISTS w_trade (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  coin_id BIGINT(20) NOT NULL,
  type INT(2) NOT NULL,
  payment_method VARCHAR(100) NOT NULL,
  margin DECIMAL(4, 2) NOT NULL,
  min_limit BIGINT(10) NOT NULL,
  max_limit BIGINT(10) NOT NULL,
  terms VARCHAR(255) NOT NULL,
  identity_id BIGINT(20) NOT NULL,
  create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (coin_id) REFERENCES w_coin(id),
  FOREIGN KEY (identity_id) REFERENCES identity(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;