CREATE TABLE IF NOT EXISTS w_coinpath (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  coin_id BIGINT(20) NOT NULL,
  path VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  create_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (coin_id) REFERENCES w_coin(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;