name: Android CI

on: push

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug APKs
        run: bash ./android/gradlew :app:assembleDebug

      - name: Upload APK dev
        uses: actions/upload-artifact@v2
        with:
          name: Dev
          path: ${{ github.workspace }}android/app/build/outputs/apk/dev/debug/app-dev-debug.apk

      - name: Upload APK prod
          uses: actions/upload-artifact@v2
          with:
            name: Prod
            path: ${{ github.workspace }}android/app/build/outputs/apk/prod/debug/app-prod-debug.apk
