package com.app.belcobtm.api.model.param
import com.google.gson.annotations.SerializedName


data class RefreshParam(
    @SerializedName("refreshToken")
    val refreshToken: String // hDkyfY1DSlRBx5SrfQr445uP2duuXUIfnSXI0PiHwNM3mmTemEvkrUlaQQyCfY09B9yHXF7mFSy1iNpxQG3H2qVl8BdjuOWCYPJ0igrDYprPppmykcHSA4qCqiuhwHfhfRM1JIhKTlaMq2P9p1YhdBYIsnlaPBF0TtnHd0RRGUNnFaOA7iEbpcYzhprb0ruRBnxu0Yc2CHvY4datvp3nNhqtMnoZZj47Io8ygeBPOS9KAiHM9YBfM244Lx
)