// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Algorand.proto

package wallet.core.jni.proto;

public final class Algorand {
  private Algorand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionPayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.TransactionPay)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string to_address = 1;</code>
     */
    java.lang.String getToAddress();
    /**
     * <code>string to_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <code>uint64 fee = 2;</code>
     */
    long getFee();

    /**
     * <code>uint64 amount = 3;</code>
     */
    long getAmount();

    /**
     * <code>uint64 first_round = 4;</code>
     */
    long getFirstRound();

    /**
     * <code>uint64 last_round = 5;</code>
     */
    long getLastRound();
  }
  /**
   * Protobuf type {@code TW.Algorand.Proto.TransactionPay}
   */
  public  static final class TransactionPay extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.TransactionPay)
      TransactionPayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionPay.newBuilder() to construct.
    private TransactionPay(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionPay() {
      toAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionPay();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionPay(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              toAddress_ = s;
              break;
            }
            case 16: {

              fee_ = input.readUInt64();
              break;
            }
            case 24: {

              amount_ = input.readUInt64();
              break;
            }
            case 32: {

              firstRound_ = input.readUInt64();
              break;
            }
            case 40: {

              lastRound_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_TransactionPay_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_TransactionPay_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Algorand.TransactionPay.class, wallet.core.jni.proto.Algorand.TransactionPay.Builder.class);
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object toAddress_;
    /**
     * <code>string to_address = 1;</code>
     */
    public java.lang.String getToAddress() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string to_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEE_FIELD_NUMBER = 2;
    private long fee_;
    /**
     * <code>uint64 fee = 2;</code>
     */
    public long getFee() {
      return fee_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>uint64 amount = 3;</code>
     */
    public long getAmount() {
      return amount_;
    }

    public static final int FIRST_ROUND_FIELD_NUMBER = 4;
    private long firstRound_;
    /**
     * <code>uint64 first_round = 4;</code>
     */
    public long getFirstRound() {
      return firstRound_;
    }

    public static final int LAST_ROUND_FIELD_NUMBER = 5;
    private long lastRound_;
    /**
     * <code>uint64 last_round = 5;</code>
     */
    public long getLastRound() {
      return lastRound_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getToAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, toAddress_);
      }
      if (fee_ != 0L) {
        output.writeUInt64(2, fee_);
      }
      if (amount_ != 0L) {
        output.writeUInt64(3, amount_);
      }
      if (firstRound_ != 0L) {
        output.writeUInt64(4, firstRound_);
      }
      if (lastRound_ != 0L) {
        output.writeUInt64(5, lastRound_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getToAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, toAddress_);
      }
      if (fee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, fee_);
      }
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, amount_);
      }
      if (firstRound_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, firstRound_);
      }
      if (lastRound_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, lastRound_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Algorand.TransactionPay)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Algorand.TransactionPay other = (wallet.core.jni.proto.Algorand.TransactionPay) obj;

      if (!getToAddress()
          .equals(other.getToAddress())) return false;
      if (getFee()
          != other.getFee()) return false;
      if (getAmount()
          != other.getAmount()) return false;
      if (getFirstRound()
          != other.getFirstRound()) return false;
      if (getLastRound()
          != other.getLastRound()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TO_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getToAddress().hashCode();
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFee());
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAmount());
      hash = (37 * hash) + FIRST_ROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFirstRound());
      hash = (37 * hash) + LAST_ROUND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastRound());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.TransactionPay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.TransactionPay prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TW.Algorand.Proto.TransactionPay}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.TransactionPay)
        wallet.core.jni.proto.Algorand.TransactionPayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_TransactionPay_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_TransactionPay_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Algorand.TransactionPay.class, wallet.core.jni.proto.Algorand.TransactionPay.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Algorand.TransactionPay.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        toAddress_ = "";

        fee_ = 0L;

        amount_ = 0L;

        firstRound_ = 0L;

        lastRound_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_TransactionPay_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.TransactionPay getDefaultInstanceForType() {
        return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.TransactionPay build() {
        wallet.core.jni.proto.Algorand.TransactionPay result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.TransactionPay buildPartial() {
        wallet.core.jni.proto.Algorand.TransactionPay result = new wallet.core.jni.proto.Algorand.TransactionPay(this);
        result.toAddress_ = toAddress_;
        result.fee_ = fee_;
        result.amount_ = amount_;
        result.firstRound_ = firstRound_;
        result.lastRound_ = lastRound_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Algorand.TransactionPay) {
          return mergeFrom((wallet.core.jni.proto.Algorand.TransactionPay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Algorand.TransactionPay other) {
        if (other == wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance()) return this;
        if (!other.getToAddress().isEmpty()) {
          toAddress_ = other.toAddress_;
          onChanged();
        }
        if (other.getFee() != 0L) {
          setFee(other.getFee());
        }
        if (other.getAmount() != 0L) {
          setAmount(other.getAmount());
        }
        if (other.getFirstRound() != 0L) {
          setFirstRound(other.getFirstRound());
        }
        if (other.getLastRound() != 0L) {
          setLastRound(other.getLastRound());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Algorand.TransactionPay parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Algorand.TransactionPay) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object toAddress_ = "";
      /**
       * <code>string to_address = 1;</code>
       */
      public java.lang.String getToAddress() {
        java.lang.Object ref = toAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string to_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        java.lang.Object ref = toAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string to_address = 1;</code>
       */
      public Builder setToAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string to_address = 1;</code>
       */
      public Builder clearToAddress() {
        
        toAddress_ = getDefaultInstance().getToAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string to_address = 1;</code>
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAddress_ = value;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>uint64 fee = 2;</code>
       */
      public long getFee() {
        return fee_;
      }
      /**
       * <code>uint64 fee = 2;</code>
       */
      public Builder setFee(long value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 fee = 2;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0L;
        onChanged();
        return this;
      }

      private long amount_ ;
      /**
       * <code>uint64 amount = 3;</code>
       */
      public long getAmount() {
        return amount_;
      }
      /**
       * <code>uint64 amount = 3;</code>
       */
      public Builder setAmount(long value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0L;
        onChanged();
        return this;
      }

      private long firstRound_ ;
      /**
       * <code>uint64 first_round = 4;</code>
       */
      public long getFirstRound() {
        return firstRound_;
      }
      /**
       * <code>uint64 first_round = 4;</code>
       */
      public Builder setFirstRound(long value) {
        
        firstRound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 first_round = 4;</code>
       */
      public Builder clearFirstRound() {
        
        firstRound_ = 0L;
        onChanged();
        return this;
      }

      private long lastRound_ ;
      /**
       * <code>uint64 last_round = 5;</code>
       */
      public long getLastRound() {
        return lastRound_;
      }
      /**
       * <code>uint64 last_round = 5;</code>
       */
      public Builder setLastRound(long value) {
        
        lastRound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 last_round = 5;</code>
       */
      public Builder clearLastRound() {
        
        lastRound_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.TransactionPay)
    }

    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.TransactionPay)
    private static final wallet.core.jni.proto.Algorand.TransactionPay DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Algorand.TransactionPay();
    }

    public static wallet.core.jni.proto.Algorand.TransactionPay getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionPay>
        PARSER = new com.google.protobuf.AbstractParser<TransactionPay>() {
      @java.lang.Override
      public TransactionPay parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionPay(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionPay> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionPay> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Algorand.TransactionPay getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * netowrk / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     */
    java.lang.String getGenesisId();
    /**
     * <pre>
     * netowrk / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGenesisIdBytes();

    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     */
    com.google.protobuf.ByteString getGenesisHash();

    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     */
    com.google.protobuf.ByteString getNote();

    /**
     * <pre>
     * private key
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    boolean hasTransactionPay();
    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    wallet.core.jni.proto.Algorand.TransactionPay getTransactionPay();
    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    wallet.core.jni.proto.Algorand.TransactionPayOrBuilder getTransactionPayOrBuilder();

    public wallet.core.jni.proto.Algorand.SigningInput.MessageOneofCase getMessageOneofCase();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      genesisId_ = "";
      genesisHash_ = com.google.protobuf.ByteString.EMPTY;
      note_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              genesisId_ = s;
              break;
            }
            case 18: {

              genesisHash_ = input.readBytes();
              break;
            }
            case 26: {

              note_ = input.readBytes();
              break;
            }
            case 34: {

              privateKey_ = input.readBytes();
              break;
            }
            case 82: {
              wallet.core.jni.proto.Algorand.TransactionPay.Builder subBuilder = null;
              if (messageOneofCase_ == 10) {
                subBuilder = ((wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_).toBuilder();
              }
              messageOneof_ =
                  input.readMessage(wallet.core.jni.proto.Algorand.TransactionPay.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_);
                messageOneof_ = subBuilder.buildPartial();
              }
              messageOneofCase_ = 10;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Algorand.SigningInput.class, wallet.core.jni.proto.Algorand.SigningInput.Builder.class);
    }

    private int messageOneofCase_ = 0;
    private java.lang.Object messageOneof_;
    public enum MessageOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      TRANSACTION_PAY(10),
      MESSAGEONEOF_NOT_SET(0);
      private final int value;
      private MessageOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageOneofCase forNumber(int value) {
        switch (value) {
          case 10: return TRANSACTION_PAY;
          case 0: return MESSAGEONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageOneofCase
    getMessageOneofCase() {
      return MessageOneofCase.forNumber(
          messageOneofCase_);
    }

    public static final int GENESIS_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object genesisId_;
    /**
     * <pre>
     * netowrk / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     */
    public java.lang.String getGenesisId() {
      java.lang.Object ref = genesisId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genesisId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * netowrk / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGenesisIdBytes() {
      java.lang.Object ref = genesisId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genesisId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENESIS_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString genesisHash_;
    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     */
    public com.google.protobuf.ByteString getGenesisHash() {
      return genesisHash_;
    }

    public static final int NOTE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString note_;
    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     */
    public com.google.protobuf.ByteString getNote() {
      return note_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * private key
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    public static final int TRANSACTION_PAY_FIELD_NUMBER = 10;
    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    public boolean hasTransactionPay() {
      return messageOneofCase_ == 10;
    }
    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    public wallet.core.jni.proto.Algorand.TransactionPay getTransactionPay() {
      if (messageOneofCase_ == 10) {
         return (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_;
      }
      return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
    }
    /**
     * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
     */
    public wallet.core.jni.proto.Algorand.TransactionPayOrBuilder getTransactionPayOrBuilder() {
      if (messageOneofCase_ == 10) {
         return (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_;
      }
      return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGenesisIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, genesisId_);
      }
      if (!genesisHash_.isEmpty()) {
        output.writeBytes(2, genesisHash_);
      }
      if (!note_.isEmpty()) {
        output.writeBytes(3, note_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(4, privateKey_);
      }
      if (messageOneofCase_ == 10) {
        output.writeMessage(10, (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGenesisIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, genesisId_);
      }
      if (!genesisHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, genesisHash_);
      }
      if (!note_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, note_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, privateKey_);
      }
      if (messageOneofCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Algorand.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Algorand.SigningInput other = (wallet.core.jni.proto.Algorand.SigningInput) obj;

      if (!getGenesisId()
          .equals(other.getGenesisId())) return false;
      if (!getGenesisHash()
          .equals(other.getGenesisHash())) return false;
      if (!getNote()
          .equals(other.getNote())) return false;
      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!getMessageOneofCase().equals(other.getMessageOneofCase())) return false;
      switch (messageOneofCase_) {
        case 10:
          if (!getTransactionPay()
              .equals(other.getTransactionPay())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GENESIS_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGenesisId().hashCode();
      hash = (37 * hash) + GENESIS_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getGenesisHash().hashCode();
      hash = (37 * hash) + NOTE_FIELD_NUMBER;
      hash = (53 * hash) + getNote().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      switch (messageOneofCase_) {
        case 10:
          hash = (37 * hash) + TRANSACTION_PAY_FIELD_NUMBER;
          hash = (53 * hash) + getTransactionPay().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.SigningInput)
        wallet.core.jni.proto.Algorand.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Algorand.SigningInput.class, wallet.core.jni.proto.Algorand.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Algorand.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        genesisId_ = "";

        genesisHash_ = com.google.protobuf.ByteString.EMPTY;

        note_ = com.google.protobuf.ByteString.EMPTY;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        messageOneofCase_ = 0;
        messageOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Algorand.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningInput build() {
        wallet.core.jni.proto.Algorand.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningInput buildPartial() {
        wallet.core.jni.proto.Algorand.SigningInput result = new wallet.core.jni.proto.Algorand.SigningInput(this);
        result.genesisId_ = genesisId_;
        result.genesisHash_ = genesisHash_;
        result.note_ = note_;
        result.privateKey_ = privateKey_;
        if (messageOneofCase_ == 10) {
          if (transactionPayBuilder_ == null) {
            result.messageOneof_ = messageOneof_;
          } else {
            result.messageOneof_ = transactionPayBuilder_.build();
          }
        }
        result.messageOneofCase_ = messageOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Algorand.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Algorand.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Algorand.SigningInput other) {
        if (other == wallet.core.jni.proto.Algorand.SigningInput.getDefaultInstance()) return this;
        if (!other.getGenesisId().isEmpty()) {
          genesisId_ = other.genesisId_;
          onChanged();
        }
        if (other.getGenesisHash() != com.google.protobuf.ByteString.EMPTY) {
          setGenesisHash(other.getGenesisHash());
        }
        if (other.getNote() != com.google.protobuf.ByteString.EMPTY) {
          setNote(other.getNote());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        switch (other.getMessageOneofCase()) {
          case TRANSACTION_PAY: {
            mergeTransactionPay(other.getTransactionPay());
            break;
          }
          case MESSAGEONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Algorand.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Algorand.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageOneofCase_ = 0;
      private java.lang.Object messageOneof_;
      public MessageOneofCase
          getMessageOneofCase() {
        return MessageOneofCase.forNumber(
            messageOneofCase_);
      }

      public Builder clearMessageOneof() {
        messageOneofCase_ = 0;
        messageOneof_ = null;
        onChanged();
        return this;
      }


      private java.lang.Object genesisId_ = "";
      /**
       * <pre>
       * netowrk / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       */
      public java.lang.String getGenesisId() {
        java.lang.Object ref = genesisId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genesisId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * netowrk / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGenesisIdBytes() {
        java.lang.Object ref = genesisId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genesisId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * netowrk / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       */
      public Builder setGenesisId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genesisId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * netowrk / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       */
      public Builder clearGenesisId() {
        
        genesisId_ = getDefaultInstance().getGenesisId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * netowrk / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       */
      public Builder setGenesisIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        genesisId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString genesisHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       */
      public com.google.protobuf.ByteString getGenesisHash() {
        return genesisHash_;
      }
      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       */
      public Builder setGenesisHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        genesisHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       */
      public Builder clearGenesisHash() {
        
        genesisHash_ = getDefaultInstance().getGenesisHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString note_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       */
      public com.google.protobuf.ByteString getNote() {
        return note_;
      }
      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       */
      public Builder setNote(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        note_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       */
      public Builder clearNote() {
        
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * private key
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * private key
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * private key
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          wallet.core.jni.proto.Algorand.TransactionPay, wallet.core.jni.proto.Algorand.TransactionPay.Builder, wallet.core.jni.proto.Algorand.TransactionPayOrBuilder> transactionPayBuilder_;
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public boolean hasTransactionPay() {
        return messageOneofCase_ == 10;
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public wallet.core.jni.proto.Algorand.TransactionPay getTransactionPay() {
        if (transactionPayBuilder_ == null) {
          if (messageOneofCase_ == 10) {
            return (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_;
          }
          return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
        } else {
          if (messageOneofCase_ == 10) {
            return transactionPayBuilder_.getMessage();
          }
          return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
        }
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public Builder setTransactionPay(wallet.core.jni.proto.Algorand.TransactionPay value) {
        if (transactionPayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageOneof_ = value;
          onChanged();
        } else {
          transactionPayBuilder_.setMessage(value);
        }
        messageOneofCase_ = 10;
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public Builder setTransactionPay(
          wallet.core.jni.proto.Algorand.TransactionPay.Builder builderForValue) {
        if (transactionPayBuilder_ == null) {
          messageOneof_ = builderForValue.build();
          onChanged();
        } else {
          transactionPayBuilder_.setMessage(builderForValue.build());
        }
        messageOneofCase_ = 10;
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public Builder mergeTransactionPay(wallet.core.jni.proto.Algorand.TransactionPay value) {
        if (transactionPayBuilder_ == null) {
          if (messageOneofCase_ == 10 &&
              messageOneof_ != wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance()) {
            messageOneof_ = wallet.core.jni.proto.Algorand.TransactionPay.newBuilder((wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_)
                .mergeFrom(value).buildPartial();
          } else {
            messageOneof_ = value;
          }
          onChanged();
        } else {
          if (messageOneofCase_ == 10) {
            transactionPayBuilder_.mergeFrom(value);
          }
          transactionPayBuilder_.setMessage(value);
        }
        messageOneofCase_ = 10;
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public Builder clearTransactionPay() {
        if (transactionPayBuilder_ == null) {
          if (messageOneofCase_ == 10) {
            messageOneofCase_ = 0;
            messageOneof_ = null;
            onChanged();
          }
        } else {
          if (messageOneofCase_ == 10) {
            messageOneofCase_ = 0;
            messageOneof_ = null;
          }
          transactionPayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public wallet.core.jni.proto.Algorand.TransactionPay.Builder getTransactionPayBuilder() {
        return getTransactionPayFieldBuilder().getBuilder();
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      public wallet.core.jni.proto.Algorand.TransactionPayOrBuilder getTransactionPayOrBuilder() {
        if ((messageOneofCase_ == 10) && (transactionPayBuilder_ != null)) {
          return transactionPayBuilder_.getMessageOrBuilder();
        } else {
          if (messageOneofCase_ == 10) {
            return (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_;
          }
          return wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
        }
      }
      /**
       * <code>.TW.Algorand.Proto.TransactionPay transaction_pay = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          wallet.core.jni.proto.Algorand.TransactionPay, wallet.core.jni.proto.Algorand.TransactionPay.Builder, wallet.core.jni.proto.Algorand.TransactionPayOrBuilder> 
          getTransactionPayFieldBuilder() {
        if (transactionPayBuilder_ == null) {
          if (!(messageOneofCase_ == 10)) {
            messageOneof_ = wallet.core.jni.proto.Algorand.TransactionPay.getDefaultInstance();
          }
          transactionPayBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              wallet.core.jni.proto.Algorand.TransactionPay, wallet.core.jni.proto.Algorand.TransactionPay.Builder, wallet.core.jni.proto.Algorand.TransactionPayOrBuilder>(
                  (wallet.core.jni.proto.Algorand.TransactionPay) messageOneof_,
                  getParentForChildren(),
                  isClean());
          messageOneof_ = null;
        }
        messageOneofCase_ = 10;
        onChanged();;
        return transactionPayBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.SigningInput)
    private static final wallet.core.jni.proto.Algorand.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Algorand.SigningInput();
    }

    public static wallet.core.jni.proto.Algorand.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Algorand.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    com.google.protobuf.ByteString getEncoded();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      encoded_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningOutput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              encoded_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Algorand.SigningOutput.class, wallet.core.jni.proto.Algorand.SigningOutput.Builder.class);
    }

    public static final int ENCODED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encoded_;
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!encoded_.isEmpty()) {
        output.writeBytes(1, encoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!encoded_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Algorand.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Algorand.SigningOutput other = (wallet.core.jni.proto.Algorand.SigningOutput) obj;

      if (!getEncoded()
          .equals(other.getEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.SigningOutput)
        wallet.core.jni.proto.Algorand.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Algorand.SigningOutput.class, wallet.core.jni.proto.Algorand.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Algorand.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        encoded_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Algorand.internal_static_TW_Algorand_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Algorand.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningOutput build() {
        wallet.core.jni.proto.Algorand.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Algorand.SigningOutput buildPartial() {
        wallet.core.jni.proto.Algorand.SigningOutput result = new wallet.core.jni.proto.Algorand.SigningOutput(this);
        result.encoded_ = encoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Algorand.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Algorand.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Algorand.SigningOutput other) {
        if (other == wallet.core.jni.proto.Algorand.SigningOutput.getDefaultInstance()) return this;
        if (other.getEncoded() != com.google.protobuf.ByteString.EMPTY) {
          setEncoded(other.getEncoded());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Algorand.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Algorand.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString encoded_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public com.google.protobuf.ByteString getEncoded() {
        return encoded_;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public Builder setEncoded(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        encoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       */
      public Builder clearEncoded() {
        
        encoded_ = getDefaultInstance().getEncoded();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Algorand.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Algorand.SigningOutput();
    }

    public static wallet.core.jni.proto.Algorand.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Algorand.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Algorand_Proto_TransactionPay_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Algorand_Proto_TransactionPay_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Algorand_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Algorand_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Algorand_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Algorand_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Algorand.proto\022\021TW.Algorand.Proto\"j\n\016T" +
      "ransactionPay\022\022\n\nto_address\030\001 \001(\t\022\013\n\003fee" +
      "\030\002 \001(\004\022\016\n\006amount\030\003 \001(\004\022\023\n\013first_round\030\004 " +
      "\001(\004\022\022\n\nlast_round\030\005 \001(\004\"\252\001\n\014SigningInput" +
      "\022\022\n\ngenesis_id\030\001 \001(\t\022\024\n\014genesis_hash\030\002 \001" +
      "(\014\022\014\n\004note\030\003 \001(\014\022\023\n\013private_key\030\004 \001(\014\022<\n" +
      "\017transaction_pay\030\n \001(\0132!.TW.Algorand.Pro" +
      "to.TransactionPayH\000B\017\n\rmessage_oneof\" \n\r" +
      "SigningOutput\022\017\n\007encoded\030\001 \001(\014B\027\n\025wallet" +
      ".core.jni.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TW_Algorand_Proto_TransactionPay_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Algorand_Proto_TransactionPay_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Algorand_Proto_TransactionPay_descriptor,
        new java.lang.String[] { "ToAddress", "Fee", "Amount", "FirstRound", "LastRound", });
    internal_static_TW_Algorand_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Algorand_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Algorand_Proto_SigningInput_descriptor,
        new java.lang.String[] { "GenesisId", "GenesisHash", "Note", "PrivateKey", "TransactionPay", "MessageOneof", });
    internal_static_TW_Algorand_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TW_Algorand_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Algorand_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Encoded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
