// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Any.proto

package wallet.core.jni.proto;

public final class Any {
  private Any() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Any.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * BIP44 network ID
     * </pre>
     *
     * <code>uint32 coin_type = 1;</code>
     */
    int getCoinType();

    /**
     * <pre>
     * JSON transaction
     * </pre>
     *
     * <code>string transaction = 2;</code>
     */
    java.lang.String getTransaction();
    /**
     * <pre>
     * JSON transaction
     * </pre>
     *
     * <code>string transaction = 2;</code>
     */
    com.google.protobuf.ByteString
        getTransactionBytes();

    /**
     * <pre>
     * Private Key in HEX format
     * </pre>
     *
     * <code>string private_key = 3;</code>
     */
    java.lang.String getPrivateKey();
    /**
     * <pre>
     * Private Key in HEX format
     * </pre>
     *
     * <code>string private_key = 3;</code>
     */
    com.google.protobuf.ByteString
        getPrivateKeyBytes();
  }
  /**
   * Protobuf type {@code TW.Any.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Any.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      transaction_ = "";
      privateKey_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              coinType_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              transaction_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              privateKey_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Any.SigningInput.class, wallet.core.jni.proto.Any.SigningInput.Builder.class);
    }

    public static final int COIN_TYPE_FIELD_NUMBER = 1;
    private int coinType_;
    /**
     * <pre>
     * BIP44 network ID
     * </pre>
     *
     * <code>uint32 coin_type = 1;</code>
     */
    public int getCoinType() {
      return coinType_;
    }

    public static final int TRANSACTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object transaction_;
    /**
     * <pre>
     * JSON transaction
     * </pre>
     *
     * <code>string transaction = 2;</code>
     */
    public java.lang.String getTransaction() {
      java.lang.Object ref = transaction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transaction_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * JSON transaction
     * </pre>
     *
     * <code>string transaction = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTransactionBytes() {
      java.lang.Object ref = transaction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transaction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object privateKey_;
    /**
     * <pre>
     * Private Key in HEX format
     * </pre>
     *
     * <code>string private_key = 3;</code>
     */
    public java.lang.String getPrivateKey() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privateKey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Private Key in HEX format
     * </pre>
     *
     * <code>string private_key = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        privateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (coinType_ != 0) {
        output.writeUInt32(1, coinType_);
      }
      if (!getTransactionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transaction_);
      }
      if (!getPrivateKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, privateKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (coinType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, coinType_);
      }
      if (!getTransactionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transaction_);
      }
      if (!getPrivateKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, privateKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Any.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Any.SigningInput other = (wallet.core.jni.proto.Any.SigningInput) obj;

      if (getCoinType()
          != other.getCoinType()) return false;
      if (!getTransaction()
          .equals(other.getTransaction())) return false;
      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COIN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCoinType();
      hash = (37 * hash) + TRANSACTION_FIELD_NUMBER;
      hash = (53 * hash) + getTransaction().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Any.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TW.Any.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Any.Proto.SigningInput)
        wallet.core.jni.proto.Any.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Any.SigningInput.class, wallet.core.jni.proto.Any.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Any.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        coinType_ = 0;

        transaction_ = "";

        privateKey_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Any.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningInput build() {
        wallet.core.jni.proto.Any.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningInput buildPartial() {
        wallet.core.jni.proto.Any.SigningInput result = new wallet.core.jni.proto.Any.SigningInput(this);
        result.coinType_ = coinType_;
        result.transaction_ = transaction_;
        result.privateKey_ = privateKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Any.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Any.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Any.SigningInput other) {
        if (other == wallet.core.jni.proto.Any.SigningInput.getDefaultInstance()) return this;
        if (other.getCoinType() != 0) {
          setCoinType(other.getCoinType());
        }
        if (!other.getTransaction().isEmpty()) {
          transaction_ = other.transaction_;
          onChanged();
        }
        if (!other.getPrivateKey().isEmpty()) {
          privateKey_ = other.privateKey_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Any.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Any.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int coinType_ ;
      /**
       * <pre>
       * BIP44 network ID
       * </pre>
       *
       * <code>uint32 coin_type = 1;</code>
       */
      public int getCoinType() {
        return coinType_;
      }
      /**
       * <pre>
       * BIP44 network ID
       * </pre>
       *
       * <code>uint32 coin_type = 1;</code>
       */
      public Builder setCoinType(int value) {
        
        coinType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * BIP44 network ID
       * </pre>
       *
       * <code>uint32 coin_type = 1;</code>
       */
      public Builder clearCoinType() {
        
        coinType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object transaction_ = "";
      /**
       * <pre>
       * JSON transaction
       * </pre>
       *
       * <code>string transaction = 2;</code>
       */
      public java.lang.String getTransaction() {
        java.lang.Object ref = transaction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transaction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * JSON transaction
       * </pre>
       *
       * <code>string transaction = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTransactionBytes() {
        java.lang.Object ref = transaction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transaction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * JSON transaction
       * </pre>
       *
       * <code>string transaction = 2;</code>
       */
      public Builder setTransaction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transaction_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON transaction
       * </pre>
       *
       * <code>string transaction = 2;</code>
       */
      public Builder clearTransaction() {
        
        transaction_ = getDefaultInstance().getTransaction();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON transaction
       * </pre>
       *
       * <code>string transaction = 2;</code>
       */
      public Builder setTransactionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        transaction_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object privateKey_ = "";
      /**
       * <pre>
       * Private Key in HEX format
       * </pre>
       *
       * <code>string private_key = 3;</code>
       */
      public java.lang.String getPrivateKey() {
        java.lang.Object ref = privateKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          privateKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Private Key in HEX format
       * </pre>
       *
       * <code>string private_key = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPrivateKeyBytes() {
        java.lang.Object ref = privateKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          privateKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Private Key in HEX format
       * </pre>
       *
       * <code>string private_key = 3;</code>
       */
      public Builder setPrivateKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private Key in HEX format
       * </pre>
       *
       * <code>string private_key = 3;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private Key in HEX format
       * </pre>
       *
       * <code>string private_key = 3;</code>
       */
      public Builder setPrivateKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        privateKey_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Any.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Any.Proto.SigningInput)
    private static final wallet.core.jni.proto.Any.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Any.SigningInput();
    }

    public static wallet.core.jni.proto.Any.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Any.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Any.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    boolean hasError();
    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    wallet.core.jni.proto.Any.SigningOutput.Error getError();
    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder getErrorOrBuilder();

    /**
     * <code>bool success = 2;</code>
     */
    boolean getSuccess();

    /**
     * <code>string output = 4;</code>
     */
    java.lang.String getOutput();
    /**
     * <code>string output = 4;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    public wallet.core.jni.proto.Any.SigningOutput.ResultCase getResultCase();
  }
  /**
   * Protobuf type {@code TW.Any.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Any.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      output_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              wallet.core.jni.proto.Any.SigningOutput.Error.Builder subBuilder = null;
              if (resultCase_ == 1) {
                subBuilder = ((wallet.core.jni.proto.Any.SigningOutput.Error) result_).toBuilder();
              }
              result_ =
                  input.readMessage(wallet.core.jni.proto.Any.SigningOutput.Error.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((wallet.core.jni.proto.Any.SigningOutput.Error) result_);
                result_ = subBuilder.buildPartial();
              }
              resultCase_ = 1;
              break;
            }
            case 16: {
              resultCase_ = 2;
              result_ = input.readBool();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              output_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Any.SigningOutput.class, wallet.core.jni.proto.Any.SigningOutput.Builder.class);
    }

    public interface ErrorOrBuilder extends
        // @@protoc_insertion_point(interface_extends:TW.Any.Proto.SigningOutput.Error)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * Error code
       * </pre>
       *
       * <code>uint32 code = 1;</code>
       */
      int getCode();

      /**
       * <pre>
       * Error description
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      java.lang.String getDescription();
      /**
       * <pre>
       * Error description
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      com.google.protobuf.ByteString
          getDescriptionBytes();
    }
    /**
     * Protobuf type {@code TW.Any.Proto.SigningOutput.Error}
     */
    public  static final class Error extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:TW.Any.Proto.SigningOutput.Error)
        ErrorOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Error.newBuilder() to construct.
      private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Error() {
        description_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Error(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                code_ = input.readUInt32();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                description_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_Error_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_Error_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Any.SigningOutput.Error.class, wallet.core.jni.proto.Any.SigningOutput.Error.Builder.class);
      }

      public static final int CODE_FIELD_NUMBER = 1;
      private int code_;
      /**
       * <pre>
       * Error code
       * </pre>
       *
       * <code>uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }

      public static final int DESCRIPTION_FIELD_NUMBER = 2;
      private volatile java.lang.Object description_;
      /**
       * <pre>
       * Error description
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * Error description
       * </pre>
       *
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (code_ != 0) {
          output.writeUInt32(1, code_);
        }
        if (!getDescriptionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (code_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, code_);
        }
        if (!getDescriptionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof wallet.core.jni.proto.Any.SigningOutput.Error)) {
          return super.equals(obj);
        }
        wallet.core.jni.proto.Any.SigningOutput.Error other = (wallet.core.jni.proto.Any.SigningOutput.Error) obj;

        if (getCode()
            != other.getCode()) return false;
        if (!getDescription()
            .equals(other.getDescription())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static wallet.core.jni.proto.Any.SigningOutput.Error parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(wallet.core.jni.proto.Any.SigningOutput.Error prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code TW.Any.Proto.SigningOutput.Error}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:TW.Any.Proto.SigningOutput.Error)
          wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_Error_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_Error_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  wallet.core.jni.proto.Any.SigningOutput.Error.class, wallet.core.jni.proto.Any.SigningOutput.Error.Builder.class);
        }

        // Construct using wallet.core.jni.proto.Any.SigningOutput.Error.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          code_ = 0;

          description_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_Error_descriptor;
        }

        @java.lang.Override
        public wallet.core.jni.proto.Any.SigningOutput.Error getDefaultInstanceForType() {
          return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
        }

        @java.lang.Override
        public wallet.core.jni.proto.Any.SigningOutput.Error build() {
          wallet.core.jni.proto.Any.SigningOutput.Error result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public wallet.core.jni.proto.Any.SigningOutput.Error buildPartial() {
          wallet.core.jni.proto.Any.SigningOutput.Error result = new wallet.core.jni.proto.Any.SigningOutput.Error(this);
          result.code_ = code_;
          result.description_ = description_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof wallet.core.jni.proto.Any.SigningOutput.Error) {
            return mergeFrom((wallet.core.jni.proto.Any.SigningOutput.Error)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(wallet.core.jni.proto.Any.SigningOutput.Error other) {
          if (other == wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance()) return this;
          if (other.getCode() != 0) {
            setCode(other.getCode());
          }
          if (!other.getDescription().isEmpty()) {
            description_ = other.description_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          wallet.core.jni.proto.Any.SigningOutput.Error parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (wallet.core.jni.proto.Any.SigningOutput.Error) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int code_ ;
        /**
         * <pre>
         * Error code
         * </pre>
         *
         * <code>uint32 code = 1;</code>
         */
        public int getCode() {
          return code_;
        }
        /**
         * <pre>
         * Error code
         * </pre>
         *
         * <code>uint32 code = 1;</code>
         */
        public Builder setCode(int value) {
          
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Error code
         * </pre>
         *
         * <code>uint32 code = 1;</code>
         */
        public Builder clearCode() {
          
          code_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object description_ = "";
        /**
         * <pre>
         * Error description
         * </pre>
         *
         * <code>string description = 2;</code>
         */
        public java.lang.String getDescription() {
          java.lang.Object ref = description_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            description_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * Error description
         * </pre>
         *
         * <code>string description = 2;</code>
         */
        public com.google.protobuf.ByteString
            getDescriptionBytes() {
          java.lang.Object ref = description_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            description_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * Error description
         * </pre>
         *
         * <code>string description = 2;</code>
         */
        public Builder setDescription(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          description_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Error description
         * </pre>
         *
         * <code>string description = 2;</code>
         */
        public Builder clearDescription() {
          
          description_ = getDefaultInstance().getDescription();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Error description
         * </pre>
         *
         * <code>string description = 2;</code>
         */
        public Builder setDescriptionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          description_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:TW.Any.Proto.SigningOutput.Error)
      }

      // @@protoc_insertion_point(class_scope:TW.Any.Proto.SigningOutput.Error)
      private static final wallet.core.jni.proto.Any.SigningOutput.Error DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new wallet.core.jni.proto.Any.SigningOutput.Error();
      }

      public static wallet.core.jni.proto.Any.SigningOutput.Error getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Error>
          PARSER = new com.google.protobuf.AbstractParser<Error>() {
        @java.lang.Override
        public Error parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Error(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Error> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Error> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningOutput.Error getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int resultCase_ = 0;
    private java.lang.Object result_;
    public enum ResultCase
        implements com.google.protobuf.Internal.EnumLite {
      ERROR(1),
      SUCCESS(2),
      RESULT_NOT_SET(0);
      private final int value;
      private ResultCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResultCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResultCase forNumber(int value) {
        switch (value) {
          case 1: return ERROR;
          case 2: return SUCCESS;
          case 0: return RESULT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResultCase
    getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public static final int ERROR_FIELD_NUMBER = 1;
    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    public boolean hasError() {
      return resultCase_ == 1;
    }
    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    public wallet.core.jni.proto.Any.SigningOutput.Error getError() {
      if (resultCase_ == 1) {
         return (wallet.core.jni.proto.Any.SigningOutput.Error) result_;
      }
      return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
    }
    /**
     * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
     */
    public wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder getErrorOrBuilder() {
      if (resultCase_ == 1) {
         return (wallet.core.jni.proto.Any.SigningOutput.Error) result_;
      }
      return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    /**
     * <code>bool success = 2;</code>
     */
    public boolean getSuccess() {
      if (resultCase_ == 2) {
        return (java.lang.Boolean) result_;
      }
      return false;
    }

    public static final int OUTPUT_FIELD_NUMBER = 4;
    private volatile java.lang.Object output_;
    /**
     * <code>string output = 4;</code>
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <code>string output = 4;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultCase_ == 1) {
        output.writeMessage(1, (wallet.core.jni.proto.Any.SigningOutput.Error) result_);
      }
      if (resultCase_ == 2) {
        output.writeBool(
            2, (boolean)((java.lang.Boolean) result_));
      }
      if (!getOutputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, output_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (wallet.core.jni.proto.Any.SigningOutput.Error) result_);
      }
      if (resultCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              2, (boolean)((java.lang.Boolean) result_));
      }
      if (!getOutputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, output_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Any.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Any.SigningOutput other = (wallet.core.jni.proto.Any.SigningOutput) obj;

      if (!getOutput()
          .equals(other.getOutput())) return false;
      if (!getResultCase().equals(other.getResultCase())) return false;
      switch (resultCase_) {
        case 1:
          if (!getError()
              .equals(other.getError())) return false;
          break;
        case 2:
          if (getSuccess()
              != other.getSuccess()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      switch (resultCase_) {
        case 1:
          hash = (37 * hash) + ERROR_FIELD_NUMBER;
          hash = (53 * hash) + getError().hashCode();
          break;
        case 2:
          hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getSuccess());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Any.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Any.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TW.Any.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Any.Proto.SigningOutput)
        wallet.core.jni.proto.Any.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Any.SigningOutput.class, wallet.core.jni.proto.Any.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Any.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        output_ = "";

        resultCase_ = 0;
        result_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Any.internal_static_TW_Any_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Any.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningOutput build() {
        wallet.core.jni.proto.Any.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Any.SigningOutput buildPartial() {
        wallet.core.jni.proto.Any.SigningOutput result = new wallet.core.jni.proto.Any.SigningOutput(this);
        if (resultCase_ == 1) {
          if (errorBuilder_ == null) {
            result.result_ = result_;
          } else {
            result.result_ = errorBuilder_.build();
          }
        }
        if (resultCase_ == 2) {
          result.result_ = result_;
        }
        result.output_ = output_;
        result.resultCase_ = resultCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Any.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Any.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Any.SigningOutput other) {
        if (other == wallet.core.jni.proto.Any.SigningOutput.getDefaultInstance()) return this;
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          onChanged();
        }
        switch (other.getResultCase()) {
          case ERROR: {
            mergeError(other.getError());
            break;
          }
          case SUCCESS: {
            setSuccess(other.getSuccess());
            break;
          }
          case RESULT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Any.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Any.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int resultCase_ = 0;
      private java.lang.Object result_;
      public ResultCase
          getResultCase() {
        return ResultCase.forNumber(
            resultCase_);
      }

      public Builder clearResult() {
        resultCase_ = 0;
        result_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          wallet.core.jni.proto.Any.SigningOutput.Error, wallet.core.jni.proto.Any.SigningOutput.Error.Builder, wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder> errorBuilder_;
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public boolean hasError() {
        return resultCase_ == 1;
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public wallet.core.jni.proto.Any.SigningOutput.Error getError() {
        if (errorBuilder_ == null) {
          if (resultCase_ == 1) {
            return (wallet.core.jni.proto.Any.SigningOutput.Error) result_;
          }
          return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
        } else {
          if (resultCase_ == 1) {
            return errorBuilder_.getMessage();
          }
          return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
        }
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public Builder setError(wallet.core.jni.proto.Any.SigningOutput.Error value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public Builder setError(
          wallet.core.jni.proto.Any.SigningOutput.Error.Builder builderForValue) {
        if (errorBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public Builder mergeError(wallet.core.jni.proto.Any.SigningOutput.Error value) {
        if (errorBuilder_ == null) {
          if (resultCase_ == 1 &&
              result_ != wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance()) {
            result_ = wallet.core.jni.proto.Any.SigningOutput.Error.newBuilder((wallet.core.jni.proto.Any.SigningOutput.Error) result_)
                .mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          if (resultCase_ == 1) {
            errorBuilder_.mergeFrom(value);
          }
          errorBuilder_.setMessage(value);
        }
        resultCase_ = 1;
        return this;
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          if (resultCase_ == 1) {
            resultCase_ = 0;
            result_ = null;
            onChanged();
          }
        } else {
          if (resultCase_ == 1) {
            resultCase_ = 0;
            result_ = null;
          }
          errorBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public wallet.core.jni.proto.Any.SigningOutput.Error.Builder getErrorBuilder() {
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      public wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder getErrorOrBuilder() {
        if ((resultCase_ == 1) && (errorBuilder_ != null)) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          if (resultCase_ == 1) {
            return (wallet.core.jni.proto.Any.SigningOutput.Error) result_;
          }
          return wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
        }
      }
      /**
       * <code>.TW.Any.Proto.SigningOutput.Error error = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          wallet.core.jni.proto.Any.SigningOutput.Error, wallet.core.jni.proto.Any.SigningOutput.Error.Builder, wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          if (!(resultCase_ == 1)) {
            result_ = wallet.core.jni.proto.Any.SigningOutput.Error.getDefaultInstance();
          }
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              wallet.core.jni.proto.Any.SigningOutput.Error, wallet.core.jni.proto.Any.SigningOutput.Error.Builder, wallet.core.jni.proto.Any.SigningOutput.ErrorOrBuilder>(
                  (wallet.core.jni.proto.Any.SigningOutput.Error) result_,
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        resultCase_ = 1;
        onChanged();;
        return errorBuilder_;
      }

      /**
       * <code>bool success = 2;</code>
       */
      public boolean getSuccess() {
        if (resultCase_ == 2) {
          return (java.lang.Boolean) result_;
        }
        return false;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder setSuccess(boolean value) {
        resultCase_ = 2;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder clearSuccess() {
        if (resultCase_ == 2) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>string output = 4;</code>
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output = 4;</code>
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string output = 4;</code>
       */
      public Builder clearOutput() {
        
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>string output = 4;</code>
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        output_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Any.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Any.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Any.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Any.SigningOutput();
    }

    public static wallet.core.jni.proto.Any.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Any.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Any_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Any_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Any_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Any_Proto_SigningOutput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Any_Proto_SigningOutput_Error_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Any_Proto_SigningOutput_Error_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tAny.proto\022\014TW.Any.Proto\"K\n\014SigningInpu" +
      "t\022\021\n\tcoin_type\030\001 \001(\r\022\023\n\013transaction\030\002 \001(" +
      "\t\022\023\n\013private_key\030\003 \001(\t\"\234\001\n\rSigningOutput" +
      "\0222\n\005error\030\001 \001(\0132!.TW.Any.Proto.SigningOu" +
      "tput.ErrorH\000\022\021\n\007success\030\002 \001(\010H\000\022\016\n\006outpu" +
      "t\030\004 \001(\t\032*\n\005Error\022\014\n\004code\030\001 \001(\r\022\023\n\013descri" +
      "ption\030\002 \001(\tB\010\n\006resultB\027\n\025wallet.core.jni" +
      ".protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TW_Any_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Any_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Any_Proto_SigningInput_descriptor,
        new java.lang.String[] { "CoinType", "Transaction", "PrivateKey", });
    internal_static_TW_Any_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Any_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Any_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Error", "Success", "Output", "Result", });
    internal_static_TW_Any_Proto_SigningOutput_Error_descriptor =
      internal_static_TW_Any_Proto_SigningOutput_descriptor.getNestedTypes().get(0);
    internal_static_TW_Any_Proto_SigningOutput_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Any_Proto_SigningOutput_Error_descriptor,
        new java.lang.String[] { "Code", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
