// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bravo.proto

package wallet.core.jni.proto;

public final class Bravo {
  private Bravo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Bravo.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Chain id (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     */
    com.google.protobuf.ByteString getChainId();

    /**
     * <pre>
     * Sender's username
     * </pre>
     *
     * <code>string sender = 2;</code>
     */
    java.lang.String getSender();
    /**
     * <pre>
     * Sender's username
     * </pre>
     *
     * <code>string sender = 2;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <pre>
     * Recipient's username
     * </pre>
     *
     * <code>string recipient = 3;</code>
     */
    java.lang.String getRecipient();
    /**
     * <pre>
     * Recipient's username
     * </pre>
     *
     * <code>string recipient = 3;</code>
     */
    com.google.protobuf.ByteString
        getRecipientBytes();

    /**
     * <pre>
     * Amount in "BRAVO" or "TEST"
     * </pre>
     *
     * <code>double amount = 4;</code>
     */
    double getAmount();

    /**
     * <pre>
     * Whether the transaction is for testnet
     * </pre>
     *
     * <code>bool testnet = 5;</code>
     */
    boolean getTestnet();

    /**
     * <pre>
     * Memo to attach to the transaction
     * </pre>
     *
     * <code>string memo = 6;</code>
     */
    java.lang.String getMemo();
    /**
     * <pre>
     * Memo to attach to the transaction
     * </pre>
     *
     * <code>string memo = 6;</code>
     */
    com.google.protobuf.ByteString
        getMemoBytes();

    /**
     * <pre>
     * Reference Block Id (160-bits)
     * </pre>
     *
     * <code>bytes reference_block_id = 7;</code>
     */
    com.google.protobuf.ByteString getReferenceBlockId();

    /**
     * <pre>
     * Timestamp on the reference block
     * </pre>
     *
     * <code>sfixed32 reference_block_time = 8;</code>
     */
    int getReferenceBlockTime();

    /**
     * <pre>
     * Sender's private key's raw bytes
     * </pre>
     *
     * <code>bytes private_key = 9;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Bravo.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Bravo.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      chainId_ = com.google.protobuf.ByteString.EMPTY;
      sender_ = "";
      recipient_ = "";
      memo_ = "";
      referenceBlockId_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              chainId_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              recipient_ = s;
              break;
            }
            case 33: {

              amount_ = input.readDouble();
              break;
            }
            case 40: {

              testnet_ = input.readBool();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              memo_ = s;
              break;
            }
            case 58: {

              referenceBlockId_ = input.readBytes();
              break;
            }
            case 69: {

              referenceBlockTime_ = input.readSFixed32();
              break;
            }
            case 74: {

              privateKey_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Bravo.SigningInput.class, wallet.core.jni.proto.Bravo.SigningInput.Builder.class);
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString chainId_;
    /**
     * <pre>
     * Chain id (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     */
    public com.google.protobuf.ByteString getChainId() {
      return chainId_;
    }

    public static final int SENDER_FIELD_NUMBER = 2;
    private volatile java.lang.Object sender_;
    /**
     * <pre>
     * Sender's username
     * </pre>
     *
     * <code>string sender = 2;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Sender's username
     * </pre>
     *
     * <code>string sender = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECIPIENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object recipient_;
    /**
     * <pre>
     * Recipient's username
     * </pre>
     *
     * <code>string recipient = 3;</code>
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Recipient's username
     * </pre>
     *
     * <code>string recipient = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private double amount_;
    /**
     * <pre>
     * Amount in "BRAVO" or "TEST"
     * </pre>
     *
     * <code>double amount = 4;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int TESTNET_FIELD_NUMBER = 5;
    private boolean testnet_;
    /**
     * <pre>
     * Whether the transaction is for testnet
     * </pre>
     *
     * <code>bool testnet = 5;</code>
     */
    public boolean getTestnet() {
      return testnet_;
    }

    public static final int MEMO_FIELD_NUMBER = 6;
    private volatile java.lang.Object memo_;
    /**
     * <pre>
     * Memo to attach to the transaction
     * </pre>
     *
     * <code>string memo = 6;</code>
     */
    public java.lang.String getMemo() {
      java.lang.Object ref = memo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memo_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Memo to attach to the transaction
     * </pre>
     *
     * <code>string memo = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMemoBytes() {
      java.lang.Object ref = memo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCE_BLOCK_ID_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString referenceBlockId_;
    /**
     * <pre>
     * Reference Block Id (160-bits)
     * </pre>
     *
     * <code>bytes reference_block_id = 7;</code>
     */
    public com.google.protobuf.ByteString getReferenceBlockId() {
      return referenceBlockId_;
    }

    public static final int REFERENCE_BLOCK_TIME_FIELD_NUMBER = 8;
    private int referenceBlockTime_;
    /**
     * <pre>
     * Timestamp on the reference block
     * </pre>
     *
     * <code>sfixed32 reference_block_time = 8;</code>
     */
    public int getReferenceBlockTime() {
      return referenceBlockTime_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Sender's private key's raw bytes
     * </pre>
     *
     * <code>bytes private_key = 9;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!chainId_.isEmpty()) {
        output.writeBytes(1, chainId_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
      }
      if (!getRecipientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recipient_);
      }
      if (amount_ != 0D) {
        output.writeDouble(4, amount_);
      }
      if (testnet_ != false) {
        output.writeBool(5, testnet_);
      }
      if (!getMemoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, memo_);
      }
      if (!referenceBlockId_.isEmpty()) {
        output.writeBytes(7, referenceBlockId_);
      }
      if (referenceBlockTime_ != 0) {
        output.writeSFixed32(8, referenceBlockTime_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(9, privateKey_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!chainId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, chainId_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
      }
      if (!getRecipientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recipient_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, amount_);
      }
      if (testnet_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, testnet_);
      }
      if (!getMemoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, memo_);
      }
      if (!referenceBlockId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, referenceBlockId_);
      }
      if (referenceBlockTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(8, referenceBlockTime_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, privateKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Bravo.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Bravo.SigningInput other = (wallet.core.jni.proto.Bravo.SigningInput) obj;

      if (!getChainId()
          .equals(other.getChainId())) return false;
      if (!getSender()
          .equals(other.getSender())) return false;
      if (!getRecipient()
          .equals(other.getRecipient())) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (getTestnet()
          != other.getTestnet()) return false;
      if (!getMemo()
          .equals(other.getMemo())) return false;
      if (!getReferenceBlockId()
          .equals(other.getReferenceBlockId())) return false;
      if (getReferenceBlockTime()
          != other.getReferenceBlockTime()) return false;
      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHAIN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChainId().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecipient().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (37 * hash) + TESTNET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTestnet());
      hash = (37 * hash) + MEMO_FIELD_NUMBER;
      hash = (53 * hash) + getMemo().hashCode();
      hash = (37 * hash) + REFERENCE_BLOCK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceBlockId().hashCode();
      hash = (37 * hash) + REFERENCE_BLOCK_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceBlockTime();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Bravo.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Bravo.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Bravo.Proto.SigningInput)
        wallet.core.jni.proto.Bravo.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Bravo.SigningInput.class, wallet.core.jni.proto.Bravo.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Bravo.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chainId_ = com.google.protobuf.ByteString.EMPTY;

        sender_ = "";

        recipient_ = "";

        amount_ = 0D;

        testnet_ = false;

        memo_ = "";

        referenceBlockId_ = com.google.protobuf.ByteString.EMPTY;

        referenceBlockTime_ = 0;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Bravo.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningInput build() {
        wallet.core.jni.proto.Bravo.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningInput buildPartial() {
        wallet.core.jni.proto.Bravo.SigningInput result = new wallet.core.jni.proto.Bravo.SigningInput(this);
        result.chainId_ = chainId_;
        result.sender_ = sender_;
        result.recipient_ = recipient_;
        result.amount_ = amount_;
        result.testnet_ = testnet_;
        result.memo_ = memo_;
        result.referenceBlockId_ = referenceBlockId_;
        result.referenceBlockTime_ = referenceBlockTime_;
        result.privateKey_ = privateKey_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Bravo.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Bravo.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Bravo.SigningInput other) {
        if (other == wallet.core.jni.proto.Bravo.SigningInput.getDefaultInstance()) return this;
        if (other.getChainId() != com.google.protobuf.ByteString.EMPTY) {
          setChainId(other.getChainId());
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getRecipient().isEmpty()) {
          recipient_ = other.recipient_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (other.getTestnet() != false) {
          setTestnet(other.getTestnet());
        }
        if (!other.getMemo().isEmpty()) {
          memo_ = other.memo_;
          onChanged();
        }
        if (other.getReferenceBlockId() != com.google.protobuf.ByteString.EMPTY) {
          setReferenceBlockId(other.getReferenceBlockId());
        }
        if (other.getReferenceBlockTime() != 0) {
          setReferenceBlockTime(other.getReferenceBlockTime());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Bravo.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Bravo.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString chainId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Chain id (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public com.google.protobuf.ByteString getChainId() {
        return chainId_;
      }
      /**
       * <pre>
       * Chain id (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public Builder setChainId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chainId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Chain id (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       */
      public Builder clearChainId() {
        
        chainId_ = getDefaultInstance().getChainId();
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <pre>
       * Sender's username
       * </pre>
       *
       * <code>string sender = 2;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Sender's username
       * </pre>
       *
       * <code>string sender = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Sender's username
       * </pre>
       *
       * <code>string sender = 2;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sender's username
       * </pre>
       *
       * <code>string sender = 2;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sender's username
       * </pre>
       *
       * <code>string sender = 2;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recipient_ = "";
      /**
       * <pre>
       * Recipient's username
       * </pre>
       *
       * <code>string recipient = 3;</code>
       */
      public java.lang.String getRecipient() {
        java.lang.Object ref = recipient_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recipient_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Recipient's username
       * </pre>
       *
       * <code>string recipient = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRecipientBytes() {
        java.lang.Object ref = recipient_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recipient_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Recipient's username
       * </pre>
       *
       * <code>string recipient = 3;</code>
       */
      public Builder setRecipient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recipient_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's username
       * </pre>
       *
       * <code>string recipient = 3;</code>
       */
      public Builder clearRecipient() {
        
        recipient_ = getDefaultInstance().getRecipient();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's username
       * </pre>
       *
       * <code>string recipient = 3;</code>
       */
      public Builder setRecipientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recipient_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <pre>
       * Amount in "BRAVO" or "TEST"
       * </pre>
       *
       * <code>double amount = 4;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * Amount in "BRAVO" or "TEST"
       * </pre>
       *
       * <code>double amount = 4;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Amount in "BRAVO" or "TEST"
       * </pre>
       *
       * <code>double amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private boolean testnet_ ;
      /**
       * <pre>
       * Whether the transaction is for testnet
       * </pre>
       *
       * <code>bool testnet = 5;</code>
       */
      public boolean getTestnet() {
        return testnet_;
      }
      /**
       * <pre>
       * Whether the transaction is for testnet
       * </pre>
       *
       * <code>bool testnet = 5;</code>
       */
      public Builder setTestnet(boolean value) {
        
        testnet_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Whether the transaction is for testnet
       * </pre>
       *
       * <code>bool testnet = 5;</code>
       */
      public Builder clearTestnet() {
        
        testnet_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object memo_ = "";
      /**
       * <pre>
       * Memo to attach to the transaction
       * </pre>
       *
       * <code>string memo = 6;</code>
       */
      public java.lang.String getMemo() {
        java.lang.Object ref = memo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          memo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Memo to attach to the transaction
       * </pre>
       *
       * <code>string memo = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMemoBytes() {
        java.lang.Object ref = memo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Memo to attach to the transaction
       * </pre>
       *
       * <code>string memo = 6;</code>
       */
      public Builder setMemo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memo to attach to the transaction
       * </pre>
       *
       * <code>string memo = 6;</code>
       */
      public Builder clearMemo() {
        
        memo_ = getDefaultInstance().getMemo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Memo to attach to the transaction
       * </pre>
       *
       * <code>string memo = 6;</code>
       */
      public Builder setMemoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memo_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString referenceBlockId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Reference Block Id (160-bits)
       * </pre>
       *
       * <code>bytes reference_block_id = 7;</code>
       */
      public com.google.protobuf.ByteString getReferenceBlockId() {
        return referenceBlockId_;
      }
      /**
       * <pre>
       * Reference Block Id (160-bits)
       * </pre>
       *
       * <code>bytes reference_block_id = 7;</code>
       */
      public Builder setReferenceBlockId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        referenceBlockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Reference Block Id (160-bits)
       * </pre>
       *
       * <code>bytes reference_block_id = 7;</code>
       */
      public Builder clearReferenceBlockId() {
        
        referenceBlockId_ = getDefaultInstance().getReferenceBlockId();
        onChanged();
        return this;
      }

      private int referenceBlockTime_ ;
      /**
       * <pre>
       * Timestamp on the reference block
       * </pre>
       *
       * <code>sfixed32 reference_block_time = 8;</code>
       */
      public int getReferenceBlockTime() {
        return referenceBlockTime_;
      }
      /**
       * <pre>
       * Timestamp on the reference block
       * </pre>
       *
       * <code>sfixed32 reference_block_time = 8;</code>
       */
      public Builder setReferenceBlockTime(int value) {
        
        referenceBlockTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp on the reference block
       * </pre>
       *
       * <code>sfixed32 reference_block_time = 8;</code>
       */
      public Builder clearReferenceBlockTime() {
        
        referenceBlockTime_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Sender's private key's raw bytes
       * </pre>
       *
       * <code>bytes private_key = 9;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * Sender's private key's raw bytes
       * </pre>
       *
       * <code>bytes private_key = 9;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sender's private key's raw bytes
       * </pre>
       *
       * <code>bytes private_key = 9;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Bravo.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Bravo.Proto.SigningInput)
    private static final wallet.core.jni.proto.Bravo.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Bravo.SigningInput();
    }

    public static wallet.core.jni.proto.Bravo.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Bravo.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Bravo.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * JSON of the signed transaction.
     * </pre>
     *
     * <code>string json_encoded = 1;</code>
     */
    java.lang.String getJsonEncoded();
    /**
     * <pre>
     * JSON of the signed transaction.
     * </pre>
     *
     * <code>string json_encoded = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonEncodedBytes();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Bravo.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Bravo.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      jsonEncoded_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              jsonEncoded_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Bravo.SigningOutput.class, wallet.core.jni.proto.Bravo.SigningOutput.Builder.class);
    }

    public static final int JSON_ENCODED_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonEncoded_;
    /**
     * <pre>
     * JSON of the signed transaction.
     * </pre>
     *
     * <code>string json_encoded = 1;</code>
     */
    public java.lang.String getJsonEncoded() {
      java.lang.Object ref = jsonEncoded_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonEncoded_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * JSON of the signed transaction.
     * </pre>
     *
     * <code>string json_encoded = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonEncodedBytes() {
      java.lang.Object ref = jsonEncoded_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonEncoded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJsonEncodedBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonEncoded_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJsonEncodedBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonEncoded_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Bravo.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Bravo.SigningOutput other = (wallet.core.jni.proto.Bravo.SigningOutput) obj;

      if (!getJsonEncoded()
          .equals(other.getJsonEncoded())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_ENCODED_FIELD_NUMBER;
      hash = (53 * hash) + getJsonEncoded().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Bravo.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Bravo.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Bravo.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Bravo.Proto.SigningOutput)
        wallet.core.jni.proto.Bravo.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Bravo.SigningOutput.class, wallet.core.jni.proto.Bravo.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Bravo.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jsonEncoded_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Bravo.internal_static_TW_Bravo_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Bravo.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningOutput build() {
        wallet.core.jni.proto.Bravo.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Bravo.SigningOutput buildPartial() {
        wallet.core.jni.proto.Bravo.SigningOutput result = new wallet.core.jni.proto.Bravo.SigningOutput(this);
        result.jsonEncoded_ = jsonEncoded_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Bravo.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Bravo.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Bravo.SigningOutput other) {
        if (other == wallet.core.jni.proto.Bravo.SigningOutput.getDefaultInstance()) return this;
        if (!other.getJsonEncoded().isEmpty()) {
          jsonEncoded_ = other.jsonEncoded_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Bravo.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Bravo.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object jsonEncoded_ = "";
      /**
       * <pre>
       * JSON of the signed transaction.
       * </pre>
       *
       * <code>string json_encoded = 1;</code>
       */
      public java.lang.String getJsonEncoded() {
        java.lang.Object ref = jsonEncoded_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonEncoded_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * JSON of the signed transaction.
       * </pre>
       *
       * <code>string json_encoded = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonEncodedBytes() {
        java.lang.Object ref = jsonEncoded_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonEncoded_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * JSON of the signed transaction.
       * </pre>
       *
       * <code>string json_encoded = 1;</code>
       */
      public Builder setJsonEncoded(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jsonEncoded_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON of the signed transaction.
       * </pre>
       *
       * <code>string json_encoded = 1;</code>
       */
      public Builder clearJsonEncoded() {
        
        jsonEncoded_ = getDefaultInstance().getJsonEncoded();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON of the signed transaction.
       * </pre>
       *
       * <code>string json_encoded = 1;</code>
       */
      public Builder setJsonEncodedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jsonEncoded_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Bravo.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Bravo.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Bravo.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Bravo.SigningOutput();
    }

    public static wallet.core.jni.proto.Bravo.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Bravo.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Bravo_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Bravo_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Bravo_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Bravo_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Bravo.proto\022\016TW.Bravo.Proto\"\301\001\n\014Signin" +
      "gInput\022\020\n\010chain_id\030\001 \001(\014\022\016\n\006sender\030\002 \001(\t" +
      "\022\021\n\trecipient\030\003 \001(\t\022\016\n\006amount\030\004 \001(\001\022\017\n\007t" +
      "estnet\030\005 \001(\010\022\014\n\004memo\030\006 \001(\t\022\032\n\022reference_" +
      "block_id\030\007 \001(\014\022\034\n\024reference_block_time\030\010" +
      " \001(\017\022\023\n\013private_key\030\t \001(\014\"%\n\rSigningOutp" +
      "ut\022\024\n\014json_encoded\030\001 \001(\tB\027\n\025wallet.core." +
      "jni.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TW_Bravo_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Bravo_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Bravo_Proto_SigningInput_descriptor,
        new java.lang.String[] { "ChainId", "Sender", "Recipient", "Amount", "Testnet", "Memo", "ReferenceBlockId", "ReferenceBlockTime", "PrivateKey", });
    internal_static_TW_Bravo_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Bravo_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Bravo_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "JsonEncoded", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
