// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Filecoin.proto

package wallet.core.jni.proto;

public final class Filecoin {
  private Filecoin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Filecoin.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Private key of sender account.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * Transaction nonce.
     * </pre>
     *
     * <code>uint64 nonce = 3;</code>
     * @return The nonce.
     */
    long getNonce();

    /**
     * <pre>
     * Transfer value.
     * </pre>
     *
     * <code>bytes value = 4;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <pre>
     * Gas limit.
     * </pre>
     *
     * <code>int64 gas_limit = 5;</code>
     * @return The gasLimit.
     */
    long getGasLimit();

    /**
     * <pre>
     * Gas fee cap.
     * </pre>
     *
     * <code>bytes gas_fee_cap = 6;</code>
     * @return The gasFeeCap.
     */
    com.google.protobuf.ByteString getGasFeeCap();

    /**
     * <pre>
     * Gas premium.
     * </pre>
     *
     * <code>bytes gas_premium = 7;</code>
     * @return The gasPremium.
     */
    com.google.protobuf.ByteString getGasPremium();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Filecoin.Proto.SigningInput}
   */
  public static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Filecoin.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      to_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      gasFeeCap_ = com.google.protobuf.ByteString.EMPTY;
      gasPremium_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              privateKey_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 24: {

              nonce_ = input.readUInt64();
              break;
            }
            case 34: {

              value_ = input.readBytes();
              break;
            }
            case 40: {

              gasLimit_ = input.readInt64();
              break;
            }
            case 50: {

              gasFeeCap_ = input.readBytes();
              break;
            }
            case 58: {

              gasPremium_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Filecoin.SigningInput.class, wallet.core.jni.proto.Filecoin.SigningInput.Builder.class);
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private key of sender account.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private volatile java.lang.Object to_;
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NONCE_FIELD_NUMBER = 3;
    private long nonce_;
    /**
     * <pre>
     * Transaction nonce.
     * </pre>
     *
     * <code>uint64 nonce = 3;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString value_;
    /**
     * <pre>
     * Transfer value.
     * </pre>
     *
     * <code>bytes value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 5;
    private long gasLimit_;
    /**
     * <pre>
     * Gas limit.
     * </pre>
     *
     * <code>int64 gas_limit = 5;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public long getGasLimit() {
      return gasLimit_;
    }

    public static final int GAS_FEE_CAP_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString gasFeeCap_;
    /**
     * <pre>
     * Gas fee cap.
     * </pre>
     *
     * <code>bytes gas_fee_cap = 6;</code>
     * @return The gasFeeCap.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasFeeCap() {
      return gasFeeCap_;
    }

    public static final int GAS_PREMIUM_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString gasPremium_;
    /**
     * <pre>
     * Gas premium.
     * </pre>
     *
     * <code>bytes gas_premium = 7;</code>
     * @return The gasPremium.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasPremium() {
      return gasPremium_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!privateKey_.isEmpty()) {
        output.writeBytes(1, privateKey_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, to_);
      }
      if (nonce_ != 0L) {
        output.writeUInt64(3, nonce_);
      }
      if (!value_.isEmpty()) {
        output.writeBytes(4, value_);
      }
      if (gasLimit_ != 0L) {
        output.writeInt64(5, gasLimit_);
      }
      if (!gasFeeCap_.isEmpty()) {
        output.writeBytes(6, gasFeeCap_);
      }
      if (!gasPremium_.isEmpty()) {
        output.writeBytes(7, gasPremium_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, privateKey_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, to_);
      }
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, nonce_);
      }
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, value_);
      }
      if (gasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, gasLimit_);
      }
      if (!gasFeeCap_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, gasFeeCap_);
      }
      if (!gasPremium_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, gasPremium_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Filecoin.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Filecoin.SigningInput other = (wallet.core.jni.proto.Filecoin.SigningInput) obj;

      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!getTo()
          .equals(other.getTo())) return false;
      if (getNonce()
          != other.getNonce()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (getGasLimit()
          != other.getGasLimit()) return false;
      if (!getGasFeeCap()
          .equals(other.getGasFeeCap())) return false;
      if (!getGasPremium()
          .equals(other.getGasPremium())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasLimit());
      hash = (37 * hash) + GAS_FEE_CAP_FIELD_NUMBER;
      hash = (53 * hash) + getGasFeeCap().hashCode();
      hash = (37 * hash) + GAS_PREMIUM_FIELD_NUMBER;
      hash = (53 * hash) + getGasPremium().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Filecoin.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Filecoin.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Filecoin.Proto.SigningInput)
        wallet.core.jni.proto.Filecoin.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Filecoin.SigningInput.class, wallet.core.jni.proto.Filecoin.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Filecoin.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        to_ = "";

        nonce_ = 0L;

        value_ = com.google.protobuf.ByteString.EMPTY;

        gasLimit_ = 0L;

        gasFeeCap_ = com.google.protobuf.ByteString.EMPTY;

        gasPremium_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Filecoin.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningInput build() {
        wallet.core.jni.proto.Filecoin.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningInput buildPartial() {
        wallet.core.jni.proto.Filecoin.SigningInput result = new wallet.core.jni.proto.Filecoin.SigningInput(this);
        result.privateKey_ = privateKey_;
        result.to_ = to_;
        result.nonce_ = nonce_;
        result.value_ = value_;
        result.gasLimit_ = gasLimit_;
        result.gasFeeCap_ = gasFeeCap_;
        result.gasPremium_ = gasPremium_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Filecoin.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Filecoin.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Filecoin.SigningInput other) {
        if (other == wallet.core.jni.proto.Filecoin.SigningInput.getDefaultInstance()) return this;
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getGasLimit() != 0L) {
          setGasLimit(other.getGasLimit());
        }
        if (other.getGasFeeCap() != com.google.protobuf.ByteString.EMPTY) {
          setGasFeeCap(other.getGasFeeCap());
        }
        if (other.getGasPremium() != com.google.protobuf.ByteString.EMPTY) {
          setGasPremium(other.getGasPremium());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Filecoin.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Filecoin.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Private key of sender account.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * Private key of sender account.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private key of sender account.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return The to.
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return The bytes for to.
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to = 2;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <pre>
       * Transaction nonce.
       * </pre>
       *
       * <code>uint64 nonce = 3;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public long getNonce() {
        return nonce_;
      }
      /**
       * <pre>
       * Transaction nonce.
       * </pre>
       *
       * <code>uint64 nonce = 3;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transaction nonce.
       * </pre>
       *
       * <code>uint64 nonce = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Transfer value.
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <pre>
       * Transfer value.
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transfer value.
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private long gasLimit_ ;
      /**
       * <pre>
       * Gas limit.
       * </pre>
       *
       * <code>int64 gas_limit = 5;</code>
       * @return The gasLimit.
       */
      @java.lang.Override
      public long getGasLimit() {
        return gasLimit_;
      }
      /**
       * <pre>
       * Gas limit.
       * </pre>
       *
       * <code>int64 gas_limit = 5;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(long value) {
        
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Gas limit.
       * </pre>
       *
       * <code>int64 gas_limit = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasFeeCap_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Gas fee cap.
       * </pre>
       *
       * <code>bytes gas_fee_cap = 6;</code>
       * @return The gasFeeCap.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasFeeCap() {
        return gasFeeCap_;
      }
      /**
       * <pre>
       * Gas fee cap.
       * </pre>
       *
       * <code>bytes gas_fee_cap = 6;</code>
       * @param value The gasFeeCap to set.
       * @return This builder for chaining.
       */
      public Builder setGasFeeCap(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasFeeCap_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Gas fee cap.
       * </pre>
       *
       * <code>bytes gas_fee_cap = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasFeeCap() {
        
        gasFeeCap_ = getDefaultInstance().getGasFeeCap();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasPremium_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Gas premium.
       * </pre>
       *
       * <code>bytes gas_premium = 7;</code>
       * @return The gasPremium.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasPremium() {
        return gasPremium_;
      }
      /**
       * <pre>
       * Gas premium.
       * </pre>
       *
       * <code>bytes gas_premium = 7;</code>
       * @param value The gasPremium to set.
       * @return This builder for chaining.
       */
      public Builder setGasPremium(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPremium_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Gas premium.
       * </pre>
       *
       * <code>bytes gas_premium = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPremium() {
        
        gasPremium_ = getDefaultInstance().getGasPremium();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Filecoin.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Filecoin.Proto.SigningInput)
    private static final wallet.core.jni.proto.Filecoin.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Filecoin.SigningInput();
    }

    public static wallet.core.jni.proto.Filecoin.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Filecoin.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Filecoin.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string json = 1;</code>
     * @return The json.
     */
    java.lang.String getJson();
    /**
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    com.google.protobuf.ByteString
        getJsonBytes();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Filecoin.Proto.SigningOutput}
   */
  public static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Filecoin.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      json_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningOutput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              json_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Filecoin.SigningOutput.class, wallet.core.jni.proto.Filecoin.SigningOutput.Builder.class);
    }

    public static final int JSON_FIELD_NUMBER = 1;
    private volatile java.lang.Object json_;
    /**
     * <code>string json = 1;</code>
     * @return The json.
     */
    @java.lang.Override
    public java.lang.String getJson() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        json_ = s;
        return s;
      }
    }
    /**
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJsonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, json_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJsonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, json_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Filecoin.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Filecoin.SigningOutput other = (wallet.core.jni.proto.Filecoin.SigningOutput) obj;

      if (!getJson()
          .equals(other.getJson())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_FIELD_NUMBER;
      hash = (53 * hash) + getJson().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Filecoin.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Filecoin.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Filecoin.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Filecoin.Proto.SigningOutput)
        wallet.core.jni.proto.Filecoin.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Filecoin.SigningOutput.class, wallet.core.jni.proto.Filecoin.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Filecoin.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        json_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Filecoin.internal_static_TW_Filecoin_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Filecoin.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningOutput build() {
        wallet.core.jni.proto.Filecoin.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Filecoin.SigningOutput buildPartial() {
        wallet.core.jni.proto.Filecoin.SigningOutput result = new wallet.core.jni.proto.Filecoin.SigningOutput(this);
        result.json_ = json_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Filecoin.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Filecoin.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Filecoin.SigningOutput other) {
        if (other == wallet.core.jni.proto.Filecoin.SigningOutput.getDefaultInstance()) return this;
        if (!other.getJson().isEmpty()) {
          json_ = other.json_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Filecoin.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Filecoin.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object json_ = "";
      /**
       * <code>string json = 1;</code>
       * @return The json.
       */
      public java.lang.String getJson() {
        java.lang.Object ref = json_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          json_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string json = 1;</code>
       * @return The bytes for json.
       */
      public com.google.protobuf.ByteString
          getJsonBytes() {
        java.lang.Object ref = json_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          json_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string json = 1;</code>
       * @param value The json to set.
       * @return This builder for chaining.
       */
      public Builder setJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        json_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string json = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJson() {
        
        json_ = getDefaultInstance().getJson();
        onChanged();
        return this;
      }
      /**
       * <code>string json = 1;</code>
       * @param value The bytes for json to set.
       * @return This builder for chaining.
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        json_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Filecoin.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Filecoin.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Filecoin.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Filecoin.SigningOutput();
    }

    public static wallet.core.jni.proto.Filecoin.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Filecoin.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Filecoin_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Filecoin_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Filecoin_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Filecoin_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Filecoin.proto\022\021TW.Filecoin.Proto\"\212\001\n\014" +
      "SigningInput\022\023\n\013private_key\030\001 \001(\014\022\n\n\002to\030" +
      "\002 \001(\t\022\r\n\005nonce\030\003 \001(\004\022\r\n\005value\030\004 \001(\014\022\021\n\tg" +
      "as_limit\030\005 \001(\003\022\023\n\013gas_fee_cap\030\006 \001(\014\022\023\n\013g" +
      "as_premium\030\007 \001(\014\"\035\n\rSigningOutput\022\014\n\004jso" +
      "n\030\001 \001(\tB\027\n\025wallet.core.jni.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TW_Filecoin_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Filecoin_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Filecoin_Proto_SigningInput_descriptor,
        new java.lang.String[] { "PrivateKey", "To", "Nonce", "Value", "GasLimit", "GasFeeCap", "GasPremium", });
    internal_static_TW_Filecoin_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Filecoin_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Filecoin_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Json", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
