// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Zilliqa.proto

package wallet.core.jni.proto;

public final class Zilliqa {
  private Zilliqa() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Zilliqa.Proto.SigningInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Transaction version
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint64 nonce = 2;</code>
     */
    long getNonce();

    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 3;</code>
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 3;</code>
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount to send (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 4;</code>
     */
    com.google.protobuf.ByteString getAmount();

    /**
     * <pre>
     * GasPrice (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 5;</code>
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <pre>
     * GasLimit
     * </pre>
     *
     * <code>uint64 gas_limit = 6;</code>
     */
    long getGasLimit();

    /**
     * <pre>
     * Private Key
     * </pre>
     *
     * <code>bytes private_key = 7;</code>
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <pre>
     * Smart contract code
     * </pre>
     *
     * <code>bytes code = 10;</code>
     */
    com.google.protobuf.ByteString getCode();

    /**
     * <pre>
     * String-ified JSON object specifying the transition parameter
     * </pre>
     *
     * <code>bytes data = 11;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Zilliqa.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Zilliqa.Proto.SigningInput)
      SigningInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningInput.newBuilder() to construct.
    private SigningInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningInput() {
      toAddress_ = "";
      amount_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      code_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningInput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 16: {

              nonce_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              toAddress_ = s;
              break;
            }
            case 34: {

              amount_ = input.readBytes();
              break;
            }
            case 42: {

              gasPrice_ = input.readBytes();
              break;
            }
            case 48: {

              gasLimit_ = input.readUInt64();
              break;
            }
            case 58: {

              privateKey_ = input.readBytes();
              break;
            }
            case 82: {

              code_ = input.readBytes();
              break;
            }
            case 90: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Zilliqa.SigningInput.class, wallet.core.jni.proto.Zilliqa.SigningInput.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * Transaction version
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private long nonce_;
    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint64 nonce = 2;</code>
     */
    public long getNonce() {
      return nonce_;
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 3;
    private volatile java.lang.Object toAddress_;
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 3;</code>
     */
    public java.lang.String getToAddress() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddress_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString amount_;
    /**
     * <pre>
     * Amount to send (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 4;</code>
     */
    public com.google.protobuf.ByteString getAmount() {
      return amount_;
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <pre>
     * GasPrice (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 5;</code>
     */
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 6;
    private long gasLimit_;
    /**
     * <pre>
     * GasLimit
     * </pre>
     *
     * <code>uint64 gas_limit = 6;</code>
     */
    public long getGasLimit() {
      return gasLimit_;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private Key
     * </pre>
     *
     * <code>bytes private_key = 7;</code>
     */
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    public static final int CODE_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString code_;
    /**
     * <pre>
     * Smart contract code
     * </pre>
     *
     * <code>bytes code = 10;</code>
     */
    public com.google.protobuf.ByteString getCode() {
      return code_;
    }

    public static final int DATA_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * String-ified JSON object specifying the transition parameter
     * </pre>
     *
     * <code>bytes data = 11;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (nonce_ != 0L) {
        output.writeUInt64(2, nonce_);
      }
      if (!getToAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toAddress_);
      }
      if (!amount_.isEmpty()) {
        output.writeBytes(4, amount_);
      }
      if (!gasPrice_.isEmpty()) {
        output.writeBytes(5, gasPrice_);
      }
      if (gasLimit_ != 0L) {
        output.writeUInt64(6, gasLimit_);
      }
      if (!privateKey_.isEmpty()) {
        output.writeBytes(7, privateKey_);
      }
      if (!code_.isEmpty()) {
        output.writeBytes(10, code_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(11, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (nonce_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, nonce_);
      }
      if (!getToAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toAddress_);
      }
      if (!amount_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, amount_);
      }
      if (!gasPrice_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, gasPrice_);
      }
      if (gasLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, gasLimit_);
      }
      if (!privateKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, privateKey_);
      }
      if (!code_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, code_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Zilliqa.SigningInput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Zilliqa.SigningInput other = (wallet.core.jni.proto.Zilliqa.SigningInput) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (getNonce()
          != other.getNonce()) return false;
      if (!getToAddress()
          .equals(other.getToAddress())) return false;
      if (!getAmount()
          .equals(other.getAmount())) return false;
      if (!getGasPrice()
          .equals(other.getGasPrice())) return false;
      if (getGasLimit()
          != other.getGasLimit()) return false;
      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNonce());
      hash = (37 * hash) + TO_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getToAddress().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount().hashCode();
      hash = (37 * hash) + GAS_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getGasPrice().hashCode();
      hash = (37 * hash) + GAS_LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasLimit());
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Zilliqa.SigningInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Zilliqa.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Zilliqa.Proto.SigningInput)
        wallet.core.jni.proto.Zilliqa.SigningInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Zilliqa.SigningInput.class, wallet.core.jni.proto.Zilliqa.SigningInput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Zilliqa.SigningInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        nonce_ = 0L;

        toAddress_ = "";

        amount_ = com.google.protobuf.ByteString.EMPTY;

        gasPrice_ = com.google.protobuf.ByteString.EMPTY;

        gasLimit_ = 0L;

        privateKey_ = com.google.protobuf.ByteString.EMPTY;

        code_ = com.google.protobuf.ByteString.EMPTY;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningInput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningInput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Zilliqa.SigningInput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningInput build() {
        wallet.core.jni.proto.Zilliqa.SigningInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningInput buildPartial() {
        wallet.core.jni.proto.Zilliqa.SigningInput result = new wallet.core.jni.proto.Zilliqa.SigningInput(this);
        result.version_ = version_;
        result.nonce_ = nonce_;
        result.toAddress_ = toAddress_;
        result.amount_ = amount_;
        result.gasPrice_ = gasPrice_;
        result.gasLimit_ = gasLimit_;
        result.privateKey_ = privateKey_;
        result.code_ = code_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Zilliqa.SigningInput) {
          return mergeFrom((wallet.core.jni.proto.Zilliqa.SigningInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Zilliqa.SigningInput other) {
        if (other == wallet.core.jni.proto.Zilliqa.SigningInput.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getNonce() != 0L) {
          setNonce(other.getNonce());
        }
        if (!other.getToAddress().isEmpty()) {
          toAddress_ = other.toAddress_;
          onChanged();
        }
        if (other.getAmount() != com.google.protobuf.ByteString.EMPTY) {
          setAmount(other.getAmount());
        }
        if (other.getGasPrice() != com.google.protobuf.ByteString.EMPTY) {
          setGasPrice(other.getGasPrice());
        }
        if (other.getGasLimit() != 0L) {
          setGasLimit(other.getGasLimit());
        }
        if (other.getPrivateKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivateKey(other.getPrivateKey());
        }
        if (other.getCode() != com.google.protobuf.ByteString.EMPTY) {
          setCode(other.getCode());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Zilliqa.SigningInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Zilliqa.SigningInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * Transaction version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * Transaction version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Transaction version
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private long nonce_ ;
      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint64 nonce = 2;</code>
       */
      public long getNonce() {
        return nonce_;
      }
      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint64 nonce = 2;</code>
       */
      public Builder setNonce(long value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint64 nonce = 2;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object toAddress_ = "";
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 3;</code>
       */
      public java.lang.String getToAddress() {
        java.lang.Object ref = toAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        java.lang.Object ref = toAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 3;</code>
       */
      public Builder setToAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 3;</code>
       */
      public Builder clearToAddress() {
        
        toAddress_ = getDefaultInstance().getToAddress();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 3;</code>
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toAddress_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString amount_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Amount to send (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 4;</code>
       */
      public com.google.protobuf.ByteString getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * Amount to send (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 4;</code>
       */
      public Builder setAmount(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Amount to send (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = getDefaultInstance().getAmount();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * GasPrice (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 5;</code>
       */
      public com.google.protobuf.ByteString getGasPrice() {
        return gasPrice_;
      }
      /**
       * <pre>
       * GasPrice (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 5;</code>
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gasPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GasPrice (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 5;</code>
       */
      public Builder clearGasPrice() {
        
        gasPrice_ = getDefaultInstance().getGasPrice();
        onChanged();
        return this;
      }

      private long gasLimit_ ;
      /**
       * <pre>
       * GasLimit
       * </pre>
       *
       * <code>uint64 gas_limit = 6;</code>
       */
      public long getGasLimit() {
        return gasLimit_;
      }
      /**
       * <pre>
       * GasLimit
       * </pre>
       *
       * <code>uint64 gas_limit = 6;</code>
       */
      public Builder setGasLimit(long value) {
        
        gasLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * GasLimit
       * </pre>
       *
       * <code>uint64 gas_limit = 6;</code>
       */
      public Builder clearGasLimit() {
        
        gasLimit_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Private Key
       * </pre>
       *
       * <code>bytes private_key = 7;</code>
       */
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <pre>
       * Private Key
       * </pre>
       *
       * <code>bytes private_key = 7;</code>
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Private Key
       * </pre>
       *
       * <code>bytes private_key = 7;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString code_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Smart contract code
       * </pre>
       *
       * <code>bytes code = 10;</code>
       */
      public com.google.protobuf.ByteString getCode() {
        return code_;
      }
      /**
       * <pre>
       * Smart contract code
       * </pre>
       *
       * <code>bytes code = 10;</code>
       */
      public Builder setCode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Smart contract code
       * </pre>
       *
       * <code>bytes code = 10;</code>
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * String-ified JSON object specifying the transition parameter
       * </pre>
       *
       * <code>bytes data = 11;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * String-ified JSON object specifying the transition parameter
       * </pre>
       *
       * <code>bytes data = 11;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * String-ified JSON object specifying the transition parameter
       * </pre>
       *
       * <code>bytes data = 11;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Zilliqa.Proto.SigningInput)
    }

    // @@protoc_insertion_point(class_scope:TW.Zilliqa.Proto.SigningInput)
    private static final wallet.core.jni.proto.Zilliqa.SigningInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Zilliqa.SigningInput();
    }

    public static wallet.core.jni.proto.Zilliqa.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningInput>
        PARSER = new com.google.protobuf.AbstractParser<SigningInput>() {
      @java.lang.Override
      public SigningInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningInput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Zilliqa.SigningInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Zilliqa.Proto.SigningOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Signed signature bytes.
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <pre>
     * JSON transaction with signature
     * </pre>
     *
     * <code>string json = 2;</code>
     */
    java.lang.String getJson();
    /**
     * <pre>
     * JSON transaction with signature
     * </pre>
     *
     * <code>string json = 2;</code>
     */
    com.google.protobuf.ByteString
        getJsonBytes();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Zilliqa.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TW.Zilliqa.Proto.SigningOutput)
      SigningOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SigningOutput.newBuilder() to construct.
    private SigningOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SigningOutput() {
      signature_ = com.google.protobuf.ByteString.EMPTY;
      json_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SigningOutput();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SigningOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              signature_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              json_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wallet.core.jni.proto.Zilliqa.SigningOutput.class, wallet.core.jni.proto.Zilliqa.SigningOutput.Builder.class);
    }

    public static final int SIGNATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString signature_;
    /**
     * <pre>
     * Signed signature bytes.
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int JSON_FIELD_NUMBER = 2;
    private volatile java.lang.Object json_;
    /**
     * <pre>
     * JSON transaction with signature
     * </pre>
     *
     * <code>string json = 2;</code>
     */
    public java.lang.String getJson() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        json_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * JSON transaction with signature
     * </pre>
     *
     * <code>string json = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJsonBytes() {
      java.lang.Object ref = json_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        json_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!signature_.isEmpty()) {
        output.writeBytes(1, signature_);
      }
      if (!getJsonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, json_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, signature_);
      }
      if (!getJsonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, json_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof wallet.core.jni.proto.Zilliqa.SigningOutput)) {
        return super.equals(obj);
      }
      wallet.core.jni.proto.Zilliqa.SigningOutput other = (wallet.core.jni.proto.Zilliqa.SigningOutput) obj;

      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!getJson()
          .equals(other.getJson())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + JSON_FIELD_NUMBER;
      hash = (53 * hash) + getJson().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static wallet.core.jni.proto.Zilliqa.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Zilliqa.SigningOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Zilliqa.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Zilliqa.Proto.SigningOutput)
        wallet.core.jni.proto.Zilliqa.SigningOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                wallet.core.jni.proto.Zilliqa.SigningOutput.class, wallet.core.jni.proto.Zilliqa.SigningOutput.Builder.class);
      }

      // Construct using wallet.core.jni.proto.Zilliqa.SigningOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        signature_ = com.google.protobuf.ByteString.EMPTY;

        json_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wallet.core.jni.proto.Zilliqa.internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningOutput getDefaultInstanceForType() {
        return wallet.core.jni.proto.Zilliqa.SigningOutput.getDefaultInstance();
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningOutput build() {
        wallet.core.jni.proto.Zilliqa.SigningOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public wallet.core.jni.proto.Zilliqa.SigningOutput buildPartial() {
        wallet.core.jni.proto.Zilliqa.SigningOutput result = new wallet.core.jni.proto.Zilliqa.SigningOutput(this);
        result.signature_ = signature_;
        result.json_ = json_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wallet.core.jni.proto.Zilliqa.SigningOutput) {
          return mergeFrom((wallet.core.jni.proto.Zilliqa.SigningOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(wallet.core.jni.proto.Zilliqa.SigningOutput other) {
        if (other == wallet.core.jni.proto.Zilliqa.SigningOutput.getDefaultInstance()) return this;
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (!other.getJson().isEmpty()) {
          json_ = other.json_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        wallet.core.jni.proto.Zilliqa.SigningOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (wallet.core.jni.proto.Zilliqa.SigningOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Signed signature bytes.
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <pre>
       * Signed signature bytes.
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Signed signature bytes.
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private java.lang.Object json_ = "";
      /**
       * <pre>
       * JSON transaction with signature
       * </pre>
       *
       * <code>string json = 2;</code>
       */
      public java.lang.String getJson() {
        java.lang.Object ref = json_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          json_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * JSON transaction with signature
       * </pre>
       *
       * <code>string json = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJsonBytes() {
        java.lang.Object ref = json_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          json_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * JSON transaction with signature
       * </pre>
       *
       * <code>string json = 2;</code>
       */
      public Builder setJson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        json_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON transaction with signature
       * </pre>
       *
       * <code>string json = 2;</code>
       */
      public Builder clearJson() {
        
        json_ = getDefaultInstance().getJson();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON transaction with signature
       * </pre>
       *
       * <code>string json = 2;</code>
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        json_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TW.Zilliqa.Proto.SigningOutput)
    }

    // @@protoc_insertion_point(class_scope:TW.Zilliqa.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Zilliqa.SigningOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new wallet.core.jni.proto.Zilliqa.SigningOutput();
    }

    public static wallet.core.jni.proto.Zilliqa.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SigningOutput>
        PARSER = new com.google.protobuf.AbstractParser<SigningOutput>() {
      @java.lang.Override
      public SigningOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigningOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SigningOutput> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public wallet.core.jni.proto.Zilliqa.SigningOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Zilliqa_Proto_SigningInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Zilliqa_Proto_SigningInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TW_Zilliqa_Proto_SigningOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rZilliqa.proto\022\020TW.Zilliqa.Proto\"\251\001\n\014Si" +
      "gningInput\022\017\n\007version\030\001 \001(\r\022\r\n\005nonce\030\002 \001" +
      "(\004\022\022\n\nto_address\030\003 \001(\t\022\016\n\006amount\030\004 \001(\014\022\021" +
      "\n\tgas_price\030\005 \001(\014\022\021\n\tgas_limit\030\006 \001(\004\022\023\n\013" +
      "private_key\030\007 \001(\014\022\014\n\004code\030\n \001(\014\022\014\n\004data\030" +
      "\013 \001(\014\"0\n\rSigningOutput\022\021\n\tsignature\030\001 \001(" +
      "\014\022\014\n\004json\030\002 \001(\tB\027\n\025wallet.core.jni.proto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TW_Zilliqa_Proto_SigningInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TW_Zilliqa_Proto_SigningInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Zilliqa_Proto_SigningInput_descriptor,
        new java.lang.String[] { "Version", "Nonce", "ToAddress", "Amount", "GasPrice", "GasLimit", "PrivateKey", "Code", "Data", });
    internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TW_Zilliqa_Proto_SigningOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TW_Zilliqa_Proto_SigningOutput_descriptor,
        new java.lang.String[] { "Signature", "Json", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
