name: Android CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    env:
      working-directory: ./android

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug APKs
        run: bash ./gradlew :app:assembleDebug
        working-directory: ${{ env.working-directory }}

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:1081646718412:android:27a7afdf467fb362ef9169"
          token: "1//0cyZChbd5pVhgCgYIARAAGAwSNQF-L9IrUx4NJuRsrsFiVI0TdliPuOx__30HKclGxK3jS1hi1iDDn58PrcD5NnFKhRoOo0ed"
          groups: testers
          file: ${{ env.working-directory }}/app/build/outputs/apk/dev/debug/app-dev-debug.apk