name: Android CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - 'android/**'

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    env:
      working-directory: ./android

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Debug
        run: bash ./gradlew assembleDebug 
        working-directory: ${{ env.working-directory }}
        
      - name: Upload artifact to Firebase App Distribution
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: /app/dest-service-acc.json
        run: bash ./gradlew assembleDebug appDistributionUploadDevDebug
        working-directory: ${{ env.working-directory }}
        
