name: Android CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - 'android/**'

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    steps:
      - uses: actions/checkout@v2
        with: 
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: NDK downloading
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT}
        
      - name: Upload artifact to Firebase App Distribution
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: ./app/dest-service-acc.json
        run: bash ./gradlew :app:assembleDevDebug :app:appDistributionUploadDevDebug 
        working-directory: ${{ env.working-directory }}
